In [63]:
import numpy as np

2 . Difference between Numpy and List in Python 

Data Type:
--------------------------
NumPy arrays are typed arrays. They store homogeneous, densely packed numerical data. In other words, all elements in a NumPy array must have the same data type.
Python lists, on the other hand, are heterogeneous. They can hold elements of varying data types.

Memory Efficiency:
--------------------------
NumPy arrays are more memory-efficient. They store data in a contiguous manner, which reduces memory overhead.
Python lists store additional information about each element, such as type and reference count. This overhead can be significant when dealing with a large number of elements.

Element-wise Operations:
--------------------------
NumPy arrays allow element-wise operations. You can perform mathematical operations on entire arrays efficiently.
Python lists do not support element-wise operations directly. You need to iterate through the list to perform operations on individual elements.

Performance:
--------------------------
NumPy arrays are optimized for numerical computations. They execute mathematical operations more efficiently than Python lists due to lower interpretation overhead.
Python lists are general-purpose data structures and are not specifically designed for numerical computations.

Memory Allocation:
--------------------------
NumPy arrays allocate memory contiguously, ensuring better performance.
Python lists may not store elements in contiguous memory locations, leading to memory fragmentation and inefficiency.

In summary, if you’re working with large datasets and need efficient numerical operations, NumPy arrays are the way to go. However, if flexibility and heterogeneous data types are essential, Python lists remain a versatile choice

In [64]:
# 3. Find the shape, size and dimension of the following array?
ar3 = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
print(f'array is \n {ar3}')

print(f'Shape of the array is  {ar3.shape}')
print(f'Size of the array is  {ar3.size}')
print(f'Dimension of the array is  {ar3.ndim}')

array is 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape of the array is  (3, 4)
Size of the array is  12
Dimension of the array is  2


In [65]:
# 4. Write python code to access the first row of the following array?
ar4 = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
print(f'array is \n {ar4}')

print(f'First row of the array is {ar4[0]}')
print(f'First row of the array in a list is {[i for i in ar4[0]]}')


array is 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row of the array is [1 2 3 4]
First row of the array in a list is [1, 2, 3, 4]


In [66]:
# 5. How do you access the element at the third row and fourth column from the given numpy array?
ar5 = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
print(f'array is \n {ar5}')

ele = ar5[2,3]
print(f"The element at the third row and fourth column is: {ele}")


array is 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
The element at the third row and fourth column is: 12


In [67]:
# 6. Write code to extract all od-indexed elements from the given numpy array?
ar6 = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
print(f'array is \n {ar6}')

ele = ar6[1::2] 
ele


array is 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[5, 6, 7, 8]])

In [68]:
# 7. How can you generate a random 3x3 matrix with values between 0 and 1?

ar7 = np.random.randint(0,2,(3,3))
print(f'random 3x3 matrix wit value between 0 and 1 is \n {ar7}')

random 3x3 matrix wit value between 0 and 1 is 
 [[0 1 1]
 [1 0 0]
 [1 0 0]]


8. Differences between np.random.rand and np.random.randn:

np.random.rand:
---------------
Generates random values from a uniform distribution over the interval [0, 1).
The generated numbers are uniformly distributed, meaning each value has an equal chance of being selected.
Example usage: np.random.rand(3, 4) creates a 3x4 array with random values between 0 and 1.


np.random.randn:
----------------
Generates random values from a standard normal distribution (also known as Gaussian distribution).
The distribution has a mean of 0 and a variance of 1.
The generated numbers follow a bell-shaped curve centered around 0.
Example usage: np.random.randn(3, 4) creates a 3x4 array with random values sampled from the standard normal distribution.
In summary:

np.random.rand produces values from a uniform distribution.
np.random.randn produces values from a standard normal distribution (Gaussian distribution) with mean 0 and variance 1123.

In [69]:
print(np.random.rand(3,4))
print(np.random.randn(3,4))

[[0.62756047 0.06570889 0.51756102 0.56791877]
 [0.97027812 0.74413656 0.82771743 0.66052018]
 [0.26250084 0.66724919 0.49638068 0.566942  ]]
[[-0.52340817 -1.15714486 -0.47584291  1.8793409 ]
 [ 1.16612447 -0.13399986 -0.34841348 -1.11517238]
 [-0.21848703 -1.04565572  1.18196206 -0.63385312]]


In [70]:
# 9. Write code to increase the dimension of the following array?

ar9 = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
print(f'array is \n {ar9}')

new_arr9 = np.expand_dims(ar9,axis=0)
print(new_arr9)
print(f'old dimension is {ar9.ndim} and new dimension is {new_arr9.ndim} ')

array is 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
old dimension is 2 and new dimension is 3 


In [71]:
# 10. How to transpose the following array in NumPy?
ar10 = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
print(f'array is \n {ar10}')

trans_ar10 = ar10.T
print(f'transposed array is \n {trans_ar10}')

array is 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
transposed array is 
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [72]:
# 11. Consider the following matrix:
A2 = np.array( [[1, 2, 3, 4] , [5, 6, 7, 8],[9, 10, 11, 12]])
B2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

print(A2)
print(B2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [73]:
# Index wiLe multiplicatio
A2*B2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [79]:
# Matix multiplicatio
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12],[1,2,3,4]])
a
b= np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12],[1,2,3,4]])
print(a)
print(b)
a @ b

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]


array([[ 42,  52,  62,  72],
       [106, 132, 158, 184],
       [170, 212, 254, 296],
       [ 42,  52,  62,  72]])

In [81]:
# Add both the matics
a+b


array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [ 2,  4,  6,  8]])

In [85]:
# Subtact matix B from A
b-a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [86]:
# Divide Matix B by A
b/a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# 12. Which function in Numpy can be used to swap the byte order of an array?

"""To swap the byte order of a NumPy array, you have two options:

 arr.newbyteorder(): This method changes the byte-ordering information in the array dtype so that it interprets the underlying
 data as being in a different byte order. For example, if you have data from a big-endian machine but want to interpret 
 it as little-endian, you can use this method1.

 arr.byteswap(): This method directly swaps the byte-ordering of the underlying data, leaving the dtype interpretation unchanged. 
 It toggles between low-endian and big-endian data representation. Note that arrays of byte-strings are not swapped using this method.

 """

In [ ]:
# 13. What is the significance of the np.linalg.inv function?

"""
The np.linalg.inv function in NumPy holds significant importance when working with matrices and linear algebra. Let me elaborate:

Matrix Inversion:
------------------
The primary purpose of np.linalg.inv is to compute the multiplicative inverse of a square matrix. Given a matrix a, it returns the matrix ainv such that:a⋅ainv​=ainv​⋅a=I
where I represents the identity matrix of the same shape as a.
This inverse matrix is crucial in solving systems of linear equations, finding eigenvalues and eigenvectors, and performing other mathematical operations.

Applications:
------------------
Linear Systems: When solving systems of linear equations, matrix inversion allows us to find the unknown variables efficiently.
Least Squares Regression: In regression analysis, the inverse matrix helps compute the coefficients that minimize the sum of squared residuals.
Eigenvalue Problems: Eigenvalues and eigenvectors are obtained using matrix inversion.
Control Theory: In control systems, matrix inversion is used for state-space representation and stability analysis.
Signal Processing: It plays a role in filtering, Fourier transforms, and convolution.

Caveats:
------------------
Ensure that the input matrix a is square (i.e., has the same number of rows and columns). Otherwise, a LinAlgError will be raised.
Matrix inversion can be computationally expensive, especially for large matrices. Consider other methods (such as solving linear systems) when possible.

In summary, np.linalg.inv is a powerful tool for handling matrix operations and is widely used in scientific computing, engineering, and data analysis
"""

In [ ]:
# 14. What does the np.reshape function do, and how is it used?

""" 
It allows to change the shape of the array without chaning the data. 

"""

In [ ]:
# 15. What is broa^casting in Numpy?

# It applies the function on operation on all the elements of the array